site_name: 'ISEN Development Environment Course'
nav:
    - Home: 'README.md'
    - Prerequisites: prerequisites.md
    - Docker Lab: docker.md
    - Kubernetes Lab: kubernetes.md
    - Getting Started on Github: github.md
    - Github Actions: actions.md
    - CI with Github Actions and Docker: ecr.md
    - Static Code Analysis: sonar.md
    - 3rd Party Dependency Check: dependency-check.md
    - Container Vulnerability Scanning with Clair: clair.md
    - Kubernetes Pod Security Policies: psp.md
    - Kubernetes Network Policies: network-policies.md
    - Git training: git.md
    - The Project: project.md
theme:
  name: 'material'
markdown_extensions:
  - codehilite
copyright: '&copy; 2020 Eric Muellenbach - eric (at) 3r1.co'