site_name: 'ISEN Secure Supply Chain Course'
nav:
    - Home: 'README.md'
    - Prerequisites: prerequisites.md
    - Docker Lab: docker.md
    - Kubernetes Lab: kubernetes.md
    - Getting Started on Github: github.md
    - Github Actions: actions.md
    - CI with Github Actions and Docker: ecr.md
    - Getting Started with AWS: aws.md
    - Cloudformation Deployment: cloudformation.md
    - Deploy Containers with ECS: ecs.md
    - Cloudformation Linting: cfn-nag.md
    - EKS Setup: eks.md
    - Juice Shop: juice-shop.md
    - Static Code Analysis: sonar.md
    - 3rd Party Dependency Check: dependency-check.md
    - Container Vulnerability Scanning with Clair: clair.md
    - Dynamic Application Security Scanning: zapproxy.md
    - Write your own Github Action: arachni.md
    - Jenkins CI Server: jenkins.md
    - Build Docker with Jenkins and Kaniko: kaniko.md
    - Kubernetes Pod Security Policies: psp.md
    - Kubernetes Network Policies: network-policies.md
    - DefectDojo: defectdojo.md
theme:
  name: 'material'
markdown_extensions:
  - codehilite
copyright: '&copy; 2020 Eric Muellenbach - eric (at) 3r1.co'